export const EventsMap = {
  USER_CREATED: 'user.created',
  CREATE_ACCOUNT: 'create.account',
  INCREMENT_BALANCE: 'account.increment-balance',
  DECREMENT_BALANCE: 'account.decrement-balance',
  CREATE_NOTIFICATION: 'create.notification',
  TRANSACTION_CREATED: 'transaction.created',
  TRANSACTION_REVERTED: 'transaction.reverted',
  MESSAGE_CREATED: 'message.created',
  CREATE_SESSION: 'create.session',
  LOAN_CREATED: 'loan.created',
  LOAN_CANCELLED: 'loan.cancelled',
  INVESTMENT_CREATED: 'investment.created',
  INVESTMENT_CANCELLED: 'investment.cancelled',
  USER_LOGGED_IN: 'user.logged-in',
  NOTIFICATION_CREATED: 'notification.created',
  NOTIFICATION_READED: 'notification.readed',
  ACCOUNT_CREATED: 'account.created',
  ACCOUNT_INCREMENT_BALANCE: 'account.increment-balance',
  ACCOUNT_DECREMENT_BALANCE: 'account.decrement-balance',
  ACCOUNT_DELETED: 'account.deleted'
} as const
