@token = 1234567890
@protocol = http
@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

GET {{protocol}}://{{host}}/user?id=s1&phoneNumber=1234567890
Content-Type: {{contentType}}